### ISSUE TITLE
Le bot ne répond pas à la commande `/role`

### ISSUE THREAD

**Issue by Arcoz0308** [Virtual-Royaume/Royaume-Discord-Bot#109]
![image](https://user-images.githubusercontent.com/62679207/194944419-4dc5caeb-7752-4d44-8ec4-20993bef7a08.png)

**Comment by Bluzzi** [comment]
L'erreur lorsqu'on exécute la commande :
```shell
D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@sapphire\shapeshift\src\validators\UnionValidator.ts:111
                return Result.err(new CombinedError(errors));
                    ^
CombinedError: Received one or more errors
    at UnionValidator.handle (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@sapphire\shapeshift\src\validators\UnionValidator.ts:111:21)
    at UnionValidator.parse (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@sapphire\shapeshift\src\validators\BaseValidator.ts:80:86)
    at EmbedBuilder.setDescription (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@discordjs\builders\src\messages\embed\Embed.ts:63:26)
    at simpleEmbed (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\src\utils\Embed.ts:8:10)
    at Role.execute (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\src\commands\list\Role.ts:48:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    ExpectedValidationError: Expected values to be equals
        at LiteralValidator.handle (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@sapphire\shapeshift\src\validators\LiteralValidator.ts:17:17)
        at LiteralValidator.run (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@sapphire\shapeshift\src\validators\BaseValidator.ts:62:21)
        at UnionValidator.handle (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@sapphire\shapeshift\src\validators\UnionValidator.ts:106:29)
        at UnionValidator.parse (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@sapphire\shapeshift\src\validators\BaseValidator.ts:80:86)
        at EmbedBuilder.setDescription (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@discordjs\builders\src\messages\embed\Embed.ts:63:26)
        at simpleEmbed (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\src\utils\Embed.ts:8:10)
        at Role.execute (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\src\commands\list\Role.ts:48:44)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      validator: 's.literal(V)',
      given: '',
      expected: null
    },
    ExpectedConstraintError: Invalid string length
        at Object.run (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@sapphire\shapeshift\src\constraints\StringConstraints.ts:40:18)
        at StringValidator.run (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@sapphire\shapeshift\src\validators\BaseValidator.ts:66:24)
        at UnionValidator.handle (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@sapphire\shapeshift\src\validators\UnionValidator.ts:106:29)
        at UnionValidator.parse (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@sapphire\shapeshift\src\validators\BaseValidator.ts:80:86)
        at EmbedBuilder.setDescription (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\node_modules\@discordjs\builders\src\messages\embed\Embed.ts:63:26)
        at simpleEmbed (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\src\utils\Embed.ts:8:10)
        at Role.execute (D:\Travail\Programmation\GitHub\Royaume\Royaume-Bot\src\commands\list\Role.ts:48:44)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      constraint: 's.string.lengthGreaterThanOrEqual',
      given: '',
      expected: 'expected.length >= 1'
    }
  ]
}
```
